spring.application.name=fraud-shield-backend
server.port=5000

# Python FastAPI Microservice Endpoint
python.ai.url=http://127.0.0.1:8000

# Cryptographic Secret for HMAC-SHA256 Challenge Derivation
security.hmac.secret=BANK-CYBER-FRAUD-GUARD-2026

# Multipart upload limits (25MB)
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB
